[fix]change file name & bakgrd color
Yilin-seniorProject/Senior-project pull request #11
Opened 2024-07-20 17:17 UTC by JustAHedgehog

1. file name change to "templates".
2. first title background color turn to gray.
3. add & change tranportation icons and add them on the map.

2024-07-20 17:25 UTC, Yilin20021016 commented on web/templates/project_members.html
> +        <div class="first_title">
loss </div>

2024-07-20 17:31 UTC, Yilin20021016 requested changes
@JustAHedgehog make tag up in project_members.html

2024-07-21 16:23 UTC, JustAHedgehog commented on web/templates/project_members.html
> +        <div class="first_title">
Okay, I added it

2024-07-21 16:28 UTC, Yilin20021016 approved these changes

2024-07-21 16:29 UTC, merged