[feat] add two 'GET' requests for back_end
Yilin-seniorProject/Senior-project pull request #23
Opened 2024-08-17 08:36 UTC by JustAHedgehog

One is for auto fetch data, and the other is for markers on osm.

2024-08-18 07:23 UTC, Yilin20021016 commented on web/templates/index.html
> +                        <input type="text" id="target_type" value="" >
readonly 不見了

2024-08-18 07:29 UTC, Yilin20021016 commented on web/templates/index.html
> +            <input type="text" id="input_lng" placeholder="Longitude"value="">
placeholder & value中間的空格補上，並檢查其他地方是否有遺漏或多餘的空格

2024-08-18 07:31 UTC, Yilin20021016 commented on web/static/js/osm.js
> +    };
沒有發送的數據請刪除

2024-08-18 07:34 UTC, Yilin20021016 commented on web/static/js/counter.js
>      const updateCountDisplay = () => {
請重新建構函式型別function，並決定其是否為匿名函式

2024-08-18 07:35 UTC, Yilin20021016 requested changes
Please check your code again. @JustAHedgehog

2024-08-18 15:35 UTC, JustAHedgehog commented on web/templates/index.html
> +            <input type="text" id="input_lng" placeholder="Longitude"value="">
好 我修好了

2024-08-20 20:01 UTC, Yilin20021016 approved these changes

2024-08-20 20:01 UTC, merged