[feat]add floating window to enlarge the image
Yilin-seniorProject/Senior-project pull request #24
Opened 2024-08-26 12:41 UTC by AkihikoSU

2024-09-05 04:37 UTC, Yilin20021016 commented on web/static/js/counter.js
> +            break;
break縮排少一層

2024-09-05 04:40 UTC, Yilin20021016 requested changes
@AkihikoSU @JustAHedgehog Please review your code and delete the part of unnecessary comments

2024-09-05 05:30 UTC, JustAHedgehog commented on web/static/js/counter.js
> +            break;
修了！

2024-09-09 14:38 UTC, Yilin20021016 approved these changes

2024-09-09 14:38 UTC, merged